version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SUPABASE_DELIVERY_URL=${SUPABASE_DELIVERY_URL}
      - SUPABASE_DELIVERY_KEY=${SUPABASE_DELIVERY_KEY}
      - SUPABASE_RESTAURANT_URL=${SUPABASE_RESTAURANT_URL}
      - SUPABASE_RESTAURANT_KEY=${SUPABASE_RESTAURANT_KEY}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: 