spring:
  application:
    name: americana-integration
  
  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    order:
      queue: order.queue
      exchange: order.exchange
      routing-key: order.routing.key

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Supabase Configuration
supabase:
  delivery:
    url: ${SUPABASE_DELIVERY_URL}
    key: ${SUPABASE_DELIVERY_KEY}
  restaurant:
    url: ${SUPABASE_RESTAURANT_URL}
    key: ${SUPABASE_RESTAURANT_KEY}

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api}

# Logging Configuration
logging:
  level:
    root: INFO
    com.americana.integration: DEBUG
    org.springframework.amqp: INFO
    com.americana: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 