spring:
  application:
    name: americana-integration
  
  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    order:
      queue: americana.orders
      exchange: americana.exchange
      routing-key: americana.orders

# JPA Configuration
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

# Supabase Configuration
supabase:
  delivery:
    url: https://zitdlgsiktyghnauhaxq.supabase.co
    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppdGRsZ3Npa3R5Z2huYXVoYXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNTcxNDIsImV4cCI6MjA1NTYzMzE0Mn0.uyBo1tUIDMvgOoBNnOXNfzVjPv3WLHoLBb7wNiM24GA
  restaurant:
    url: https://bawostbfbkadpsggljfm.supabase.co
    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhd29zdGJmYmthZHBzZ2dsamZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwODAxNzYsImV4cCI6MjA1NTY1NjE3Nn0.-40P5GnJCweyONWNXASLcZAZ7DM7ZA8d8X401Zy5L6o

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

# Logging Configuration
logging:
  level:
    root: INFO
    com.americana.integration: DEBUG
    org.springframework.amqp: INFO
    com.americana: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
    org.springframework.security: DEBUG 